<?php
/**
 * SINTA Widget Image Generator
 * Generate dynamic SINTA profile badge
 */

header('Content-Type: image/png');
header('Cache-Control: public, max-age=3600'); // Cache 1 jam

// Ambil ID SINTA dari parameter
$sintaId = isset($_GET['id']) ? intval($_GET['id']) : 0;

if ($sintaId <= 0) {
    generateErrorImage("Invalid SINTA ID");
    exit;
}

// Fungsi untuk fetch data dari SINTA API
function getSintaData($id) {
    $url = "https://api-gateway.sinta.kemdikbud.go.id/v1/authors/profile/{$id}";
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($httpCode == 200 && $response) {
        return json_decode($response, true);
    }
    
    return null;
}

// Ambil data SINTA
$data = getSintaData($sintaId);

if (!$data) {
    generateErrorImage("Data not found");
    exit;
}

// Extract informasi penting
$name = isset($data['name']) ? $data['name'] : 'Unknown';
$affiliation = isset($data['affiliation']['name']) ? $data['affiliation']['name'] : '-';
$scopusHIndex = isset($data['scopus_h_index']) ? $data['scopus_h_index'] : 0;
$scopusCitations = isset($data['scopus_citations']) ? $data['scopus_citations'] : 0;
$googleHIndex = isset($data['google_h_index']) ? $data['google_h_index'] : 0;
$googleCitations = isset($data['google_citations']) ? $data['google_citations'] : 0;

// Ukuran gambar
$width = 600;
$height = 350;

// Buat gambar
$image = imagecreatetruecolor($width, $height);

// Warna
$white = imagecolorallocate($image, 255, 255, 255);
$black = imagecolorallocate($image, 33, 33, 33);
$darkGray = imagecolorallocate($image, 100, 100, 100);
$lightGray = imagecolorallocate($image, 240, 240, 240);
$blue = imagecolorallocate($image, 41, 128, 185);
$green = imagecolorallocate($image, 39, 174, 96);
$orange = imagecolorallocate($image, 230, 126, 34);
$borderColor = imagecolorallocate($image, 220, 220, 220);

// Background putih
imagefilledrectangle($image, 0, 0, $width, $height, $white);

// Border
imagerectangle($image, 0, 0, $width - 1, $height - 1, $borderColor);

// Header dengan background biru
imagefilledrectangle($image, 0, 0, $width, 80, $blue);

// Judul
$fontPath = __DIR__ . '/fonts/arial.ttf'; // Pastikan Anda punya font
$title = "SINTA Profile";

// Jika font file tidak ada, gunakan fungsi dasar
if (file_exists($fontPath)) {
    imagettftext($image, 24, 0, 20, 50, $white, $fontPath, $title);
    imagettftext($image, 16, 0, 20, 110, $black, $fontPath, truncateText($name, 45));
    imagettftext($image, 12, 0, 20, 135, $darkGray, $fontPath, truncateText($affiliation, 60));
} else {
    // Fallback ke font bawaan
    imagestring($image, 5, 20, 30, $title, $white);
    imagestring($image, 4, 20, 90, truncateText($name, 50), $black);
    imagestring($image, 3, 20, 115, truncateText($affiliation, 65), $darkGray);
}

// Statistik
$yStart = 170;
$lineHeight = 40;

// Scopus H-Index
drawStatBox($image, 20, $yStart, 260, "Scopus H-Index", $scopusHIndex, $orange, $fontPath);

// Scopus Citations
drawStatBox($image, 300, $yStart, 260, "Scopus Citations", number_format($scopusCitations), $green, $fontPath);

// Google Scholar H-Index
drawStatBox($image, 20, $yStart + $lineHeight + 20, 260, "GS H-Index", $googleHIndex, $blue, $fontPath);

// Google Scholar Citations
drawStatBox($image, 300, $yStart + $lineHeight + 20, 260, "GS Citations", number_format($googleCitations), $orange, $fontPath);

// Footer - Link ke blog Anda (untuk backlink)
$footerText = "Generated by YourBlog.com"; // Ganti dengan blog Anda
if (file_exists($fontPath)) {
    imagettftext($image, 10, 0, 20, $height - 15, $darkGray, $fontPath, $footerText);
} else {
    imagestring($image, 2, 20, $height - 20, $footerText, $darkGray);
}

// Output gambar
imagepng($image);
imagedestroy($image);

// Fungsi helper
function drawStatBox($image, $x, $y, $width, $label, $value, $color, $fontPath) {
    global $lightGray, $black, $darkGray;
    
    // Background box
    imagefilledrectangle($image, $x, $y, $x + $width, $y + 35, $lightGray);
    
    if (file_exists($fontPath)) {
        imagettftext($image, 10, 0, $x + 10, $y + 17, $darkGray, $fontPath, $label);
        imagettftext($image, 16, 0, $x + 10, $y + 32, $color, $fontPath, $value);
    } else {
        imagestring($image, 2, $x + 10, $y + 5, $label, $darkGray);
        imagestring($image, 5, $x + 10, $y + 18, $value, $color);
    }
}

function truncateText($text, $maxLength) {
    if (strlen($text) > $maxLength) {
        return substr($text, 0, $maxLength - 3) . '...';
    }
    return $text;
}

function generateErrorImage($message) {
    $image = imagecreatetruecolor(400, 100);
    $white = imagecolorallocate($image, 255, 255, 255);
    $red = imagecolorallocate($image, 231, 76, 60);
    
    imagefilledrectangle($image, 0, 0, 400, 100, $white);
    imagestring($image, 4, 20, 40, "Error: " . $message, $red);
    
    imagepng($image);
    imagedestroy($image);
}
?>
